services:
  latentsync:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TZ=Asia/Shanghai
    ports:
      - "7860:7860"
    volumes:
      - D:\home\models\checkpoints:/workspace/LatentSync/checkpoints
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - http_proxy=http://192.168.1.5:10808
      - https_proxy=http://192.168.1.5:10808
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
    devices:
      - nvidia.com/gpu=all
    security_opt:
       - label=disable
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
  #  command: ["--lang", "zh-tw"]  # Options: "en", "ja", "zh-tw"
